theme = "ryder"
enableGitInfo = false

[params]
  env = "production"
  analytics_provider = "posthog"
  posthog_host = "https://t.benstrawbridge.com"
  posthog_ui_host = "https://us.posthog.com"
  posthog_defaults = "2026-01-30"
  posthog_person_profiles = "identified_only"

# [services]
#   [services.googleAnalytics]
#     ID = 'G-6ZYXDDEJQW'
